name: deploy-aws-lambda

on:
  push:
    branches:
      - master  # Trigger on push to master branch, modify this if needed.

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'CPAS-microservices.sln'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Install AWS Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Publish .NET application
        run: dotnet publish -c Release -o ./publish

      - name: Package Lambda function
        run: dotnet lambda package --configuration Release --output-package ./deployment/my-lambda-package.zip

      - name: Deploy to AWS Lambda
        run: |
          dotnet lambda update-function-code UserWebApi-8Oct \
            --package ./deployment/my-lambda-package.zip \
            --region ap-southeast-1
